### ISSUE TITLE
Evaluation Technologien

### ISSUE THREAD

**Issue by manuelroth** [manuelroth/osm2vectortiles-thesis#20] opened 2015-10-06 11:08 UTC
- [ ] Import Tools, Schema
- [ ] Tileserver: Tessera, Apache + Renderd
- [ ] Mbtiles versus Geo Package
- [ ] Wikimedia Stack

**Comment by lukasmartinelli** [comment] 2015-11-20 12:47
Duplicate of #33

**Closed as completed by lukasmartinelli** 2015-11-20 12:47 UTC
Labels: documentation
